export const TYPOGRAPHY_POSITIVE_TEST_TEXT = 'typography'
export const TYPOGRAPHY_NEGATIVE_TEST_TEXT = 'negative-test'
export const ICON_DATA_TESTID = 'icon-comp'
export const SEARCH_CARDS = 'Search cards'
export const ICONBUTTON_TESTID = 'icon-button'
