export const TYPOGRAPHY_POSITIVE_TEST_TEXT = 'typography'
export const TYPOGRAPHY_NEGATIVE_TEST_TEXT = 'negative-test'
export const ICON_DATA_TESTID = 'icon-comp'
export const QUICKBOOKS_CATEGORY_OPTION = ['Expense', 'Travel','Travel meals', 'Hotels']
export const QUICKBOOKS_CATEGORY_DROPDOWN_PLACEHOLDER = 'Choose one'
export const LABEL_VALUE_CARD_TEST_LABEL = 'Potential Savings'
export const LABEL_VALUE_CARD_TEST_VALUE = '$5,000.00'
export const AUGUST_SPEND_TEXT = 'August spend'
export const AUGUST_SPEND_AMOUNT = '$12,198.72'
export const SEARCH_SUGGESTION_CARD_HEADER_TEXT = 'Show all results for '
export const TRANSACTIONS = 'TRANSACTIONS'
export const SEARCH_SUGGESTION_CARD_FOOTER_TEXT = 'Search tips'
export const SEARCHED_TEXT = 'Lyft'
export const SEARCH_SUGGESTION_TEST_ID = 'search-suggestion-card'
export const ICONBUTTON_TESTID = 'icon-button'
export const SEARCH_CARDS = 'Search cards'
export const MERCHANT_RULE_MODAL_HEADING = 'Create merchant rule'
export const MERCHANT_RULE_CONTENT_FIRST_HALF = 'Set a default QuickBooks Category for '
export const MERCHANT_RULE_CONTENT_SECOND_HALF = 'This rule will be applied automatically to all unsynced and future transactions from '
export const MERCHANT_RULE_MODAL_CONTENT = 'Set a default QuickBooks Category for "Lyft". This rule will be applied automatically to all unsynced and future transactions from "Lyft".'
export const MERCHANT_RULE_MODAL_TRANSACTIONS_INFO = '42 unsynced transactions'
export const ACCOUNTING_TABLE_HEADINGS = ['Transactions', 'AMOUNT ', 'DATE', 'USER', 'QUICKBOOKS CATEGORY', 'RECEIPT', 'MEMO', 'SYNC']
export const SYNC_BUTTON_TEST = 'Make ready'
export const PAGINATION_RESULTS_MOCK_COUNT = '919 results'
export const PAGINATION_NEXT_BUTTON_LABEL = 'Next'
export const PAGINATION_PREV_BUTTON_LABEL = 'Previous'
export const SPENDING_GRAPH_TEST_ID = 'spending-graph'
export const RAMPCARDS_TEXT = 'Ramp cards'
export const MISSING_ITEMS  = 'Missing items'
export const MERCHANT_RULES  = 'Merchant rules'
export const CATEGORY_RULES  = 'Category rules'
export const DEPARTMENT_RULES  = 'Department rules'
export const LOCATION_RULES  = 'Location rules'
export const MISSING_ITEMS_MOCK_VALUE  = 79
export const CATEGORY_RULES_MOCK_VALUE  = 3
export const DEPARTMENT_RULES_MOCK_VALUE  = 0
export const LOCATION_RULES_MOCK_VALUE  = 0
export const MERCHANT_RULES_MOCK_VALUE  = 2
export const SETUP_GUIDE = 'Setup guide'
export const NavBarButtonLabels = ['Insights', 'Transactions', 'Cards', 'Company', 'Bill pay','Vendors','Reimbursement','Accounting' ]
export const REPORTING_CARD_HEADING = 'Partner reward found'
export const REPORTING_CARD_CONTENT = "You're paying for Amazon Web Services - leverage our partnership"
export const REPORTING_CARD_POTENTIAL_SAVINGS_TEXT = 'Potential Savings'
export const REPORTING_CARD_POTENTIAL_SAVINGS_VALUE = '$5,000.00'
export const REPORTING_CARD_FOOTER_BUTTON_LABEL = 'Go to partner reward'
